// Archetype base rates: % of a simulated population whose nearest prototype
// is each archetype. Generated by simulateBaseRates(500_000, BASE_RATE_SEED)
// in lib/rarity.ts — a correlated multivariate-normal trait population
// (TRAIT_CORR) run through matchArchetypes. The test suite re-runs a smaller
// seeded simulation and asserts these constants stay honest. Estimates
// against provisional norms; labeled as such wherever shown.

export const BASE_RATE_SEED = 7901;

export const ARCHETYPE_BASE_RATES: Record<string, number> = {
  "The Operator": 17.5,
  "The Explorer": 17.3,
  "The Driver": 16.6,
  "The Diplomat": 12.9,
  "The Steward": 11.9,
  "The Scholar": 10.0,
  "The Catalyst": 7.7,
  "The Architect": 6.2,
};
